worker_processes 1;
daemon off;

error_log stderr;

events {
  worker_connections 1024;
}

http {
  charset utf-8;
  include mime.types;
  default_type application/octet-stream;
  sendfile on;

  server {
    listen {{env "PORT"}};
    root /workspace;
    index index.html;

    location / {
      try_files $uri $uri/ =404;
    }
  }
}
